export const indoSukukBondAbi = [
  [
    { inputs: [], stateMutability: "nonpayable", type: "constructor" },
    { inputs: [], name: "Address_Seized", type: "error" },
    { inputs: [], name: "EnforcedPause", type: "error" },
    { inputs: [], name: "Error_AddressAlreadyBlacklisted", type: "error" },
    { inputs: [], name: "Error_AddressAlreadySeized", type: "error" },
    { inputs: [], name: "Error_AddressBlacklistedOrSeized", type: "error" },
    { inputs: [], name: "Error_BlacklistedAddress", type: "error" },
    { inputs: [], name: "Error_FinalAmountExceedMaximumYield", type: "error" },
    { inputs: [], name: "Error_InvalidZeroAddress", type: "error" },
    { inputs: [], name: "Error_InvestmentAlreadyWithdrawn", type: "error" },
    {
      inputs: [],
      name: "Error_InvestmentAmountExceedMaximumInvestmentAmount",
      type: "error",
    },
    { inputs: [], name: "Error_InvestmentHashAlreadyExists", type: "error" },
    { inputs: [], name: "Error_InvestmentIdNotFound", type: "error" },
    { inputs: [], name: "Error_InvestmentNotFound", type: "error" },
    { inputs: [], name: "Error_InvestmentNotMatured", type: "error" },
    {
      inputs: [],
      name: "Error_InvestmentWithdrawalAlreadyAllowed",
      type: "error",
    },
    { inputs: [], name: "Error_NotInvestmentOwnerNorAdmin", type: "error" },
    { inputs: [], name: "Error_ProductDurationAlreadyExists", type: "error" },
    { inputs: [], name: "Error_ProductNotEnabled", type: "error" },
    { inputs: [], name: "Error_ProductNotFound", type: "error" },
    { inputs: [], name: "Error_ReasonableYieldPercentage", type: "error" },
    {
      inputs: [],
      name: "Error_ThisTokenInsufficientTokenBalance",
      type: "error",
    },
    { inputs: [], name: "Error_UnsupportedToken", type: "error" },
    { inputs: [], name: "Error_ZeroDuration", type: "error" },
    { inputs: [], name: "Error_ZeroInvestmentAmount", type: "error" },
    { inputs: [], name: "Error_ZeroTokenAddress", type: "error" },
    { inputs: [], name: "ExpectedPause", type: "error" },
    { inputs: [], name: "InvalidInitialization", type: "error" },
    { inputs: [], name: "NotInitializing", type: "error" },
    {
      inputs: [{ internalType: "address", name: "owner", type: "address" }],
      name: "OwnableInvalidOwner",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "account", type: "address" }],
      name: "OwnableUnauthorizedAccount",
      type: "error",
    },
    { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_address",
          type: "address",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "_isBlacklisted",
          type: "bool",
        },
      ],
      name: "BlacklistedAddress",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint64",
          name: "version",
          type: "uint64",
        },
      ],
      name: "Initialized",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "investorAddress",
          type: "address",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "productId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "startDate",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "maturityDate",
          type: "uint256",
        },
      ],
      name: "InvestmentCreated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "investorAddress",
          type: "address",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "productId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "isWithdrawn",
          type: "bool",
        },
      ],
      name: "InvestmentEmergencyWithdrawn",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "investorAddress",
          type: "address",
        },
        {
          indexed: true,
          internalType: "bytes32",
          name: "investmentId",
          type: "bytes32",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "amount",
          type: "uint256",
        },
      ],
      name: "InvestmentWithdrawn",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "tokenAddress",
          type: "address",
        },
      ],
      name: "NewTokenAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "account",
          type: "address",
        },
      ],
      name: "Paused",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "duration",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint16",
          name: "yieldPercentage",
          type: "uint16",
        },
      ],
      name: "ProductAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "durations",
          type: "uint256",
        },
        { indexed: false, internalType: "bool", name: "enabled", type: "bool" },
      ],
      name: "ProductEnabled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_address",
          type: "address",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "_isSeized",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "string",
          name: "_ipfsReason",
          type: "string",
        },
      ],
      name: "SeizedAddress",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "tokenAddress",
          type: "address",
        },
      ],
      name: "TokenRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address",
          name: "account",
          type: "address",
        },
      ],
      name: "Unpaused",
      type: "event",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_duration", type: "uint256" },
        { internalType: "uint16", name: "_yieldPercentage", type: "uint16" },
      ],
      name: "addProduct",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_maxAllTvl", type: "uint256" },
      ],
      name: "adminChangeMaxAllTvl",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_maxPerUserTvl", type: "uint256" },
      ],
      name: "adminChangeMaxPerUserTvl",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "adminSeeTokenBalance",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
      name: "adminWithdrawToken",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "allowedToken",
      outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_productDuration", type: "uint256" },
        { internalType: "bool", name: "_enabled", type: "bool" },
      ],
      name: "alterProduct",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "blacklistedAddresses",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_productId", type: "uint256" },
        { internalType: "uint256", name: "_amount", type: "uint256" },
      ],
      name: "deposit",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_userAddress", type: "address" },
        { internalType: "bytes32", name: "_investmentId", type: "bytes32" },
      ],
      name: "getInvestment",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "startDate", type: "uint256" },
            { internalType: "uint256", name: "maturityDate", type: "uint256" },
            { internalType: "uint256", name: "productId", type: "uint256" },
            {
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "initialInvestedAmount",
              type: "uint256",
            },
            { internalType: "uint256", name: "finalAmount", type: "uint256" },
            { internalType: "bool", name: "allowWithdrawal", type: "bool" },
            { internalType: "bool", name: "isWithdrawn", type: "bool" },
          ],
          internalType: "struct UserInvestment",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_productId", type: "uint256" },
      ],
      name: "getProduct",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "duration", type: "uint256" },
            { internalType: "bool", name: "enabled", type: "bool" },
            { internalType: "uint16", name: "yieldPercentage", type: "uint16" },
          ],
          internalType: "struct InvestmentProduct",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_userAddress", type: "address" },
        { internalType: "bytes32", name: "_investmentId", type: "bytes32" },
      ],
      name: "getUserInvestmentProjectedYield",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_userAddress", type: "address" },
      ],
      name: "getUserInvestments",
      outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_owner", type: "address" },
        { internalType: "address", name: "_allowedToken", type: "address" },
        {
          internalType: "uint256",
          name: "_maximumAllInvestment",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_maximumInvestmentPerUser",
          type: "uint256",
        },
      ],
      name: "initialize",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "investmentProducts",
      outputs: [
        { internalType: "uint256", name: "duration", type: "uint256" },
        { internalType: "bool", name: "enabled", type: "bool" },
        { internalType: "uint16", name: "yieldPercentage", type: "uint16" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "maximumAllInvestment",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "maximumInvestmentPerUser",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "paused",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "seizedInvestments",
      outputs: [
        { internalType: "bool", name: "isSeized", type: "bool" },
        { internalType: "string", name: "ipfsReason", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
      name: "sendTokenToContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bool", name: "_isBlacklisted", type: "bool" },
      ],
      name: "setBlacklistStatus",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "bool", name: "_paused", type: "bool" }],
      name: "setPaused",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bool", name: "_isSeized", type: "bool" },
        { internalType: "string", name: "_ipfsReason", type: "string" },
      ],
      name: "setSeizedStatus",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "totalTVL",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_userAddress", type: "address" },
        { internalType: "bytes32", name: "_investmentId", type: "bytes32" },
      ],
      name: "updateState",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "bytes32", name: "", type: "bytes32" },
      ],
      name: "userInvestments",
      outputs: [
        { internalType: "uint256", name: "startDate", type: "uint256" },
        { internalType: "uint256", name: "maturityDate", type: "uint256" },
        { internalType: "uint256", name: "productId", type: "uint256" },
        { internalType: "address", name: "investorAddress", type: "address" },
        {
          internalType: "uint256",
          name: "initialInvestedAmount",
          type: "uint256",
        },
        { internalType: "uint256", name: "finalAmount", type: "uint256" },
        { internalType: "bool", name: "allowWithdrawal", type: "bool" },
        { internalType: "bool", name: "isWithdrawn", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "userInvestmentsList",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "userTVL",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "_investmentId", type: "bytes32" },
      ],
      name: "withdraw",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
];

export const allowedTokenAbi = [
  {
    inputs: [
      { internalType: "string", name: "name_", type: "string" },
      { internalType: "string", name: "symbol_", type: "string" },
      { internalType: "uint8", name: "decimals_", type: "uint8" },
      { internalType: "address", name: "owner_", type: "address" },
      { internalType: "address[]", name: "initialHolders_", type: "address[]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "allowance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientAllowance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "approver", type: "address" }],
    name: "ERC20InvalidApprover",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "receiver", type: "address" }],
    name: "ERC20InvalidReceiver",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "sender", type: "address" }],
    name: "ERC20InvalidSender",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "spender", type: "address" }],
    name: "ERC20InvalidSpender",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];